### PR TITLE
README.md: point to development docs for the installation from source

### PR DESCRIPTION
**Pull request by yegorich**
Also fix a typo and the section depth.

### CODE REVIEW

**Comment by yegorich** [comment]
@mtwebster @clefebvre could you please review this PR?

**Comment by yegorich** [comment]
Btw, what about removing the `INSTALL` file?

**Comment by sskras** [comment]
Looks reasonable enough (to a passer by).

**Comment by mtwebster** [comment]
Removed INSTALL file, thanks
https://github.com/linuxmint/timeshift/commit/ef07b2c1377a77aeffd299ff076dd092954e8930

**Pull request merged**
