### PR TITLE
Create man page from timeshift's help output

### PR DESCRIPTION
**Pull request by yegorich**
Use `help2man` utility to create a man page.

Also remove `man/timeshift.1.gz` as Linux distros provide own hooks to compress man pages.

Depends on #175

### CODE REVIEW

**Comment by yegorich** [comment]
Man page generation is working now. During the deb file creation, `timeshift.1` will be automatically compressed.

**Comment by hosiet** [comment]
Hi,

Thanks for your work, this looks good to me.

Just one minor issue: will you consider leaving a copy of plain-text `timeshift.1` in `man/` directory as part of the source code, just like previously we left a copy of `timeshift.1.gz` there? If we do so, that file could act as a fallback when `help2man` is not available. This will be useful in scenarios when `help2man` is not working, such as during cross-compilation where executing cross-built `timeshift` binary is not available.

**Comment by hosiet** [comment]
Of course, in this case we would expect someone to update the copy of `man/timeshift.1` in source code from time to time... which can be part of the release procedure and won't cause too much hustle.

**Comment by mtwebster** [comment]
Can you rebase this? It was broken by 0c8a853c9d6d8f64baefeecbc9ff02cf862323dd (Build-Depends change).

**Comment by yegorich** [comment]
meson PR already creates man pages from the help output. In thoery, we can drop it.

**Comment by yegorich** [comment]
I have rebased this PR and tried to make the changes more compatible with meson PR.

**Pull request merged**
