### PR TITLE
Fix the desktop file name + project license in appdata

### PR DESCRIPTION
**Pull request by AsciiWolf**
The correct name seems to be `timeshift-gtk.desktop`.

/cc @clefebvre @suve

### CODE REVIEW

**Comment by yegorich** [comment]
While at this, project's license should be changed to `GPL-2.0-or-later`.

**Comment by AsciiWolf** [comment]
Good point! Added.

**Comment by yegorich** [comment]
I am not that sure that we should change the [id tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic). Perhaps, it is better to add a [binary provides](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-provides) tag instead?

**Comment by AsciiWolf** [comment]
We should definitely change the id tag since it does not match the actual desktop file. Binary provides would most likely won't work - since AppStream still needs to match the correct desktop file for desktop icon etc.

Another solution would be to rename the AppStream (and AppStream id) + desktop files to a proper rDNS name (or at least change the AppStream file name/id + add `<launchable type="desktop-id">timeshift-gtk.desktop</launchable>`), however I think that for now, just changing the id in current AppStream file to match the actual desktop file name will be the easiest solution.

**Comment by yegorich** [comment]
OK. I agree

**Pull request merged**
